### ISSUE TITLE
random_fromlist needs better error handling

### ISSUE THREAD

**Issue by GarysCorner** [GarysCorner/nodentd#8]
When the nameprovider is going through a text file it does a poor job validating names, additional out only supports posix end of line

**Comment by ghost** [comment]
My pull request may be useful for this.

**Comment by GarysCorner** [comment]
I like it and when I have a minute I will have to merge it, but I may need to alter the regex, because ident protocol is actually super permisive as far as allow ASCII characters

The identifier is an unformatted octet string - - all
     octets are permissible EXCEPT octal 000 (NUL), 012 (LF)
     and 015 (CR).  N.B. - space characters (040) following the
     colon separator ARE part of the identifier string and
     may not be ignored. A response string is still
     terminated normally by a CR/LF.  N.B. A string may be
     printable, but is not _necessarily_ printable.

**Comment by ghost** [comment]
Right on, glad to help. Forking and pulling with git is way easier than I had first made it out to be
